#!/bin/bash

library_folder="libs/"

declare -a libs=(
    "Adafruit-GFX-Library-1.11.9"
    "Adafruit_BusIO-1.15.0"
    "DHT-sensor-library-1.4.6"
    "Adafruit_Sensor-1.1.14"
    "Adafruit_SSD1306-2.5.9"
    "Keypad-3.1.1"
)

libraries_options=""

for lib_name in "${libs[@]}"
do
    libraries_options+="  --library ${library_folder}${lib_name}"
done

arduino-cli compile -b arduino:avr:mega $libraries_options src/
